
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.DbCon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class Sample extends javax.swing.JFrame {

    public Sample() {
        initComponents();
        info();
    }

    DbCon con = new DbCon();
    
    

    PreparedStatement ps;
    ResultSet rs;
    String sql = "insert into info(name,phonenumber,gender,date,hobby)values (?,?,?,?,?,)";

    String[] columns = {"ID", "Name", "Phone Numbe","Gender","Date","Hobby"};
// create Method
    public void info() {

        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(columns);

        jTable1.setModel(model);
        sql = "select *from info";

        try {
            ps = con.getCon().prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {

                int id = rs.getInt("idinfo");
                String name = rs.getString("name");
                int phonenumber = rs.getInt("phonenumber");
                String gender = rs.getString("gender");
//                String hobby = rs.getString("hobby");
//                String subject = rs.getString("subject");
                String date = rs.getString("date");
                String hobby = rs.getString("hobby");

                model.addRow(new Object[]{id, name, phonenumber,gender,date});

            }
            rs.close();
            ps.close();
            con.getCon().close();

        } catch (SQLException ex) {
            Logger.getLogger(Sample.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // Create method Gender
    public String getGenders(){
        String gender="";
        if (maleRadioButton.isSelected()) {
            gender= "Male";
        }
        else if(feMaleRadioButton.isSelected()){
            gender= "Female";
        
        }
        
        return gender;

    }
    
    // Date format method
    // convert to util date to sql date
    public static Date convertDateToUtilsql(java.util.Date utilDate){
    
        if (utilDate != null) {
            
            return new Date (utilDate.getTime());
        }
    
    return null;
    }
    
    // Date method String to utill
    
    public java.util.Date convertStringToDate(String dateString){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-DD");
        try {
            return dateFormat.parse(dateString);
            
            
        } catch (ParseException ex) {
            System.out.println("Paring failed"+ex);
            Logger.getLogger(Sample.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    public List<String> getHobby(){
        List<String> hobbyList = new ArrayList<>();
        if (checkCodig.isSelected()) {
            hobbyList.add("Coding");  
        }
        if (checkGaming.isSelected()) {
            hobbyList.add("Gmaing");  
        }
        return hobbyList;
    }
    
//    public String getHobby(){
//        
//        List hobby = new ArrayList();
//        
//        if (checkPrograming.isSelected()) {
//            hobby.add("Programing");
//        }
//        if (checkTraveling.isSelected()) {
//            hobby.add("Traveling");
//        }
//        if (checkWrinting.isSelected()) {
//            hobby.add("Wrinting");
//        }
//        
//        
//   
//    
//    return hobby;
//    }
//    
    

    /**
     * Creates new form Sample
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtIdinfo = new javax.swing.JTextField();
        txtNameInfo = new javax.swing.JTextField();
        txtPhoneNumberInfo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSaveInfo = new javax.swing.JButton();
        btnUpdateInfo = new javax.swing.JButton();
        btnResetInfo = new javax.swing.JButton();
        btnDeleteInfo = new javax.swing.JButton();
        maleRadioButton = new javax.swing.JRadioButton();
        feMaleRadioButton = new javax.swing.JRadioButton();
        subjectComboBox = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        checkCodig = new javax.swing.JCheckBox();
        checkGaming = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phone Number");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Subject");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Date");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gender");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hobby");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 460));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdinfo.setBorder(null);
        txtIdinfo.setCaretColor(new java.awt.Color(51, 51, 51));
        jPanel3.add(txtIdinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));
        jPanel3.add(txtNameInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));
        jPanel3.add(txtPhoneNumberInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 30));

        jTable1.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.ScrollPane.Border.color"));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 420, 210));

        btnSaveInfo.setBackground(new java.awt.Color(153, 255, 153));
        btnSaveInfo.setText("Save");
        btnSaveInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveInfoMouseClicked(evt);
            }
        });
        jPanel3.add(btnSaveInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 110, 50));

        btnUpdateInfo.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdateInfo.setText("Update");
        btnUpdateInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateInfoMouseClicked(evt);
            }
        });
        jPanel3.add(btnUpdateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 110, 50));

        btnResetInfo.setBackground(new java.awt.Color(255, 102, 102));
        btnResetInfo.setText("Reset");
        btnResetInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetInfoMouseClicked(evt);
            }
        });
        jPanel3.add(btnResetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 120, 40));

        btnDeleteInfo.setBackground(java.awt.Color.red);
        btnDeleteInfo.setText("Delete");
        btnDeleteInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteInfoMouseClicked(evt);
            }
        });
        jPanel3.add(btnDeleteInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 110, 40));

        buttonGroup1.add(maleRadioButton);
        maleRadioButton.setText("Male");
        jPanel3.add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        buttonGroup1.add(feMaleRadioButton);
        feMaleRadioButton.setText("Female");
        jPanel3.add(feMaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        subjectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<SELECT>>", "JEE", "C#", "PHP ", "DDD" }));
        jPanel3.add(subjectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 30));
        jPanel3.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 170, 30));

        checkCodig.setText("coding");
        jPanel3.add(checkCodig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        checkGaming.setText("Gaming");
        jPanel3.add(checkGaming, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 600, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveInfoMouseClicked
        // TODO add your handling code here:
        sql = "insert into info(name,phonenumber,gender,date,hobby)values (?,?,?,?,?)";

        try {
            ps = con.getCon().prepareStatement(sql);
            ps.setString(1, txtNameInfo.getText().trim());
            ps.setInt(2, Integer.parseInt(txtPhoneNumberInfo.getText().trim()));
            ps.setString(3, getGenders());
           
            ps.setDate(4, convertDateToUtilsql(dateChooser.getDate()));
            ps.setString(5, getHobby().toString());
            
            ps.executeUpdate();
            ps.close();
            con.getCon().close();

            JOptionPane.showMessageDialog(rootPane, "Data Saved");
            info();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Data not Save");

            Logger.getLogger(Sample.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSaveInfoMouseClicked

    private void btnUpdateInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateInfoMouseClicked
        // TODO add your handling code here:

        sql = "update info set name=?, phonenumber=? where idinfo=?";

        try {
            ps = con.getCon().prepareStatement(sql);
            ps.setString(1, txtNameInfo.getText().trim());
            ps.setInt(2, Integer.parseInt(txtPhoneNumberInfo.getText().trim()));
            ps.setInt(3, Integer.parseInt(txtIdinfo.getText().trim()));

            ps.executeUpdate();
            ps.close();
            con.getCon().close();
            JOptionPane.showMessageDialog(rootPane, "Data update");
            info();

        } catch (SQLException ex) {
            Logger.getLogger(Sample.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnUpdateInfoMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int row = jTable1.getSelectedRow();

        String id = jTable1.getModel().getValueAt(row, 0).toString();
        String name = jTable1.getModel().getValueAt(row, 1).toString();
        String cell = jTable1.getModel().getValueAt(row, 2).toString();
        String gender = jTable1.getModel().getValueAt(row, 3).toString();
//        String hobby = jTable1.getModel().getValueAt(row, 4).toString();
//        String subject = jTable1.getModel().getValueAt(row, 5).toString();
        String date = jTable1.getModel().getValueAt(row, 4).toString();
       
        checkCodig.setSelected(false);
        checkGaming.setSelected(false);
        
        String hobby = jTable1.getModel().getValueAt(row, 5).toString();
        
        if (hobby.contains("Coding")) {
            checkCodig.setSelected(true);
        }
        if (hobby.contains("Gaming")) {
            checkCodig.setSelected(true);
        }

        txtIdinfo.setText(id);
        txtNameInfo.setText(name);
        txtPhoneNumberInfo.setText(cell);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnResetInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetInfoMouseClicked
        // TODO add your handling code here:
        
        txtIdinfo.setText("");
        txtNameInfo.setText("");
        txtPhoneNumberInfo.setText("");
        
    }//GEN-LAST:event_btnResetInfoMouseClicked

    private void btnDeleteInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteInfoMouseClicked
        // TODO add your handling code here:
        
        sql = "delete from info where idinfo=? ";
        
        try {
            ps=con.getCon().prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(txtIdinfo.getText().trim()));
            
            ps.executeUpdate();
            ps.close();
            con.getCon().close();
            
            JOptionPane.showMessageDialog(rootPane, "Data Deleted");
            info();
            
        } catch (SQLException ex) {
  JOptionPane.showMessageDialog(rootPane, "Data not Delete");

            Logger.getLogger(Sample.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteInfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteInfo;
    private javax.swing.JButton btnResetInfo;
    private javax.swing.JButton btnSaveInfo;
    private javax.swing.JButton btnUpdateInfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkCodig;
    private javax.swing.JCheckBox checkGaming;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JRadioButton feMaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JTextField txtIdinfo;
    private javax.swing.JTextField txtNameInfo;
    private javax.swing.JTextField txtPhoneNumberInfo;
    // End of variables declaration//GEN-END:variables
}
