/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.atm.management.system;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.DataBaseConnection;

/**
 *
 * @author Dell
 */
public class Balance extends javax.swing.JFrame {
    
    DataBaseConnection con = new DataBaseConnection();

    PreparedStatement ps;
    ResultSet rs, rs1;
    String sql = "";


    /**
     * Creates new form Blance
     */
    private MainMenu mainMenu;
    public Balance(MainMenu mainMenu) {
        initComponents();
        
        this.mainMenu=mainMenu;
    }
    
     int MyAccNum;
    
    public Balance(int AccNum) {
        initComponents();
        MyAccNum=AccNum;
        accNumLb.setText(""+AccNum);
        getBalance();
   
    }
    
    int oldBlance;
    
       private void getBalance() {
        String sql = "select * from accountinfo where accId="+MyAccNum+";";

        try {
            ps = con.getCon().prepareStatement(sql);

           rs1= ps.executeQuery();
            

            if (rs1.next()) {
                oldBlance = rs1.getInt(9);
                balanceLb.setText(""+oldBlance);
                
            } else {
                //  JOptionPane.showMessageDialog(this, " ");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        accNumLb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        balanceLb = new javax.swing.JLabel();
        btnBalanceCheck = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Current Account Balance is Tk");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 30));

        accNumLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accNumLb.setForeground(new java.awt.Color(255, 0, 51));
        accNumLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(accNumLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Your Account Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 30));

        balanceLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        balanceLb.setForeground(new java.awt.Color(255, 0, 51));
        balanceLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(balanceLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 30));

        btnBalanceCheck.setIcon(new javax.swing.ImageIcon("E:\\GitHub\\SecondPartJava\\Bank ATM Management System\\icon\\undo.png")); // NOI18N
        btnBalanceCheck.setText("Back");
        btnBalanceCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBalanceCheckMouseClicked(evt);
            }
        });
        jPanel1.add(btnBalanceCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\GitHub\\SecondPartJava\\Bank ATM Management System\\icon\\atm2.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBalanceCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceCheckMouseClicked
        // TODO add your handling code here:
        dispose();
        mainMenu.setVisible(true);
        
    }//GEN-LAST:event_btnBalanceCheckMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                MainMenu mainMenu = new MainMenu();
                Balance blance = new Balance(mainMenu);
                blance.setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accNumLb;
    private javax.swing.JLabel balanceLb;
    private javax.swing.JButton btnBalanceCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
