/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.atm.management.system;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.DataBaseConnection;


public class Deposit extends javax.swing.JFrame {

    DataBaseConnection con = new DataBaseConnection();

    PreparedStatement ps;
    ResultSet rs, rs1;
    String sql = "";

    /**
     * Creates new form Deposit
     */
    private MainMenu mainMenu;

    public Deposit(MainMenu mainMenu) {
        initComponents();
        this.mainMenu = mainMenu;
        getBalance();
    }
    int MyAccNum;
    

    public Deposit(int AccNum) {
        initComponents();
        MyAccNum=AccNum;
        getBalance();
   
    }

    int oldBlance;
    

    private void getBalance() {
        String sql = "select * from accountinfo where accId="+MyAccNum+";";
            ResultSet resultSet;
        try {
            ps = con.getCon().prepareStatement(sql);

           resultSet= ps.executeQuery();
            

            if (resultSet.next()) {
                oldBlance = resultSet.getInt("balance");
                
            } else {
                //  JOptionPane.showMessageDialog(this, " ");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        amountDeposit = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        btnBackDeposit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Atm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER AMOUNT YOU WANT TO DEPOSIT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 260, 37));
        jPanel1.add(amountDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 230, 30));

        btnDeposit.setText("DEPOSIT");
        btnDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepositMouseClicked(evt);
            }
        });
        jPanel1.add(btnDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 150, 30));

        btnBackDeposit.setIcon(new javax.swing.ImageIcon("E:\\GitHub\\SecondPartJava\\Bank ATM Management System\\icon\\undo.png")); // NOI18N
        btnBackDeposit.setText("BACK");
        btnBackDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackDepositMouseClicked(evt);
            }
        });
        btnBackDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDepositActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 150, 30));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 146, 100, 20));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        Atm.setIcon(new javax.swing.ImageIcon("E:\\GitHub\\SecondPartJava\\Bank ATM Management System\\icon\\atm2.jpg")); // NOI18N
        jPanel1.add(Atm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getDate(){
        
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat();
        String myDate = s.format(d);
   
    }
    private void depositMoney(){
    
    
    }
    
    private void btnBackDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackDepositMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBackDepositMouseClicked

    private void btnBackDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDepositActionPerformed
        // TODO add your handling code here:
        dispose();
        mainMenu.setVisible(true);
        mainMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBackDepositActionPerformed

    private void btnDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositMouseClicked
        // TODO add your handling code here:

        if (amountDeposit.getText().isEmpty() || amountDeposit.getText().equals(0)) {
            JOptionPane.showMessageDialog(rootPane, "Enter the valid Amount");
        } else {
            String sql = "Update accountinfo set balance=? where accId=?";
            try {
                ps = con.getCon().prepareStatement(sql);
                ps.setInt(1,  oldBlance+Integer.valueOf(amountDeposit.getText().trim()));
                ps.setInt(2, MyAccNum);

                if (ps.executeUpdate()==1) {
                    JOptionPane.showMessageDialog(rootPane, "Balance Update");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Missing Update");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);

                Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDepositMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                MainMenu mainMenu = new MainMenu();
                Deposit deposit = new Deposit(mainMenu);
                deposit.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atm;
    private javax.swing.JTextField amountDeposit;
    private javax.swing.JButton btnBackDeposit;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
